{{- if not .Values.statuscake.existingSecret }}
{{- if not (or .Values.statuscake.username .Values.statuscake.apiKey)  }}
{{- fail "Must provide a username and APIKey if you are not supplying an existing secret" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "secretName" . }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    app: "{{ .Release.Name }}"
type: generic
data:
  USERNAME: {{ .Values.statuscake.username | b64enc }}
  API_KEY: {{ .Values.statuscake.apiKey | b64enc }}
{{- end }}
