---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-api-token"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    app: "{{ .Release.Name }}"
type: generic
data:
  USERNAME: {{ .Values.statuscake.username | b64enc }}
  API_KEY: {{ .Values.statuscake.apiKey | b64enc }}
